{
  "trabajo": [
    "Si tuvieras que despedir a alguien del área de diseño por Google Chat, ¿a quién elegirías y cuál sería tu primera frase?",
    "¿Qué cliente merece que su campaña más importante 'accidentalmente' no se ponga en vivo?",
    "Nombra a la persona que más probablemente está trabajando desde la cama en este momento.",
    "Si tuvieras que cambiar de rol con alguien del área de cuentas por un mes, ¿quién crees que sufriría más, tú o esa persona?",
    "¿Qué compañero de trabajo crees que sobreviviría menos tiempo en una apocalipsis zombie?",
    "Si pudieras ponerle un 'mute' permanente a una persona en todas las reuniones de Google Meet, ¿quién sería?",
    "Confiesa un error tuyo que le echaste la culpa a un compañero (o a la tecnología).",
    "¿A quién nominarías para que dé una presentación al cliente más difícil... con solo 5 minutos de preparación?",
    "Si la empresa se fusionara y solo pudieras salvar a un departamento, ¿cuál sacrificarías para salvar al resto?",
    "¿Qué eslogan honesto le pondrías a nuestra agencia?",
    "¿Quién del equipo crees que tiene una doble vida como espía internacional?",
    "Si descubrieras la contraseña del email del director, ¿qué sería lo primero que buscarías?",
    "Describe la personalidad de un cliente usando solo nombres de películas.",
    "¿Qué compañero crees que usa más la excusa de 'mala conexión a internet'?",
    "Si tuvieras que vivir con un cliente por una semana, ¿cuál elegirías para que la tortura sea menor?",
    "¿Cuál es el peor 'feedback' que has recibido de un cliente o de un jefe?",
    "Si tuvieras que hacer un 'roast' de un minuto sobre el área de medios, ¿qué dirías?",
    "¿Quién es la persona más propensa a responder un correo a las 3 AM?",
    "Si tuvieras que tatuarte el logo de un cliente, ¿cuál sería y en qué parte del cuerpo para que nadie lo vea?",
    "Nombra a la persona que probablemente tiene 50 pestañas abiertas en su navegador ahora mismo.",
    "¿Qué reunión recurrente eliminarías de nuestros calendarios para siempre?",
    "Si pudieras automatizar el trabajo de una persona del equipo, ¿quién se quedaría sin chamba?",
    "¿Cuál fue la idea más ridícula propuesta por un cliente que casi aceptamos?",
    "Si los sueldos se basaran en cuánto habla cada uno en las reuniones, ¿quién sería el millonario?",
    "¿Qué es algo que todos piensan sobre trabajar en publicidad que es una completa mentira?",
    "Confiesa tu peor hábito trabajando desde casa.",
    "Si tuvieras que confiarle a un compañero el acceso a tu cuenta bancaria, ¿a quién NO elegirías jamás?",
    "¿Qué presentación o reporte has hecho con el mínimo esfuerzo posible y aun así todos te felicitaron?",
    "Si un cliente te llama un viernes a las 8pm, ¿quién del equipo crees que contestaría más rápido?",
    "Describe la última 'crisis' de la agencia con el título de una canción.",
    "Si tuvieras que usar el 'outfit' de un compañero para una reunión presencial, ¿el de quién elegirías para pasar más vergüenza?",
    "¿Qué pregunta de un cliente te ha dejado completamente en blanco?",
    "Si pudieras filtrar el historial de Emojis de Google Chat de alguien, ¿el de quién te daría más curiosidad?",
    "¿Quién del equipo sería el mejor en venderle hielo a un esquimal?",
    "Si tuvieras que poner a dos directores a competir en un reality show, ¿en cuál sería y quién ganaría?",
    "Confiesa una 'mejora' a una campaña que hiciste sin decirle a nadie y funcionó.",
    "¿Cuál es el término o la palabra de 'marketero' que más odias?",
    "Si el presupuesto de 'pauta' de un cliente se convirtiera en dinero para la fiesta de la agencia, ¿a qué cliente sacrificarías?",
    "¿Quién del equipo es más propenso a tener una crisis existencial a mitad de un proyecto?",
    "Si tuvieras que describir el área de innovación con un meme, ¿cuál sería?",
    "¿Qué es lo más raro que has visto o escuchado en el fondo de una llamada de Google Meet?",
    "Si tuvieras que elegir a un compañero para que negocie tu próximo aumento de sueldo, ¿a quién elegirías?",
    "¿Qué tarea de tu día a día te quita las ganas de vivir?",
    "Si un día el internet se cae globalmente, ¿quién del equipo sería el más inútil?",
    "Confiesa un 'conocimiento técnico' que finges tener pero que siempre buscas en Google.",
    "¿Cuál de nuestros procesos internos es el más innecesariamente complicado?",
    "Si tuvieras que explicarle a tu abuela lo que hacemos en la agencia, ¿cómo se lo dirías?",
    "¿Quién es la persona que siempre propone ideas que son imposibles de ejecutar con el presupuesto que tenemos?",
    "Si el 'Asistente de Google' pudiera hacer tu trabajo por un día, ¿qué crees que haría mejor que tú?",
    "¿Qué proyecto te ha dado más ganas de lanzar tu laptop por la ventana?",
    "Si pudieras ver las métricas de vida de tus compañeros, ¿qué KPI te interesaría más ver? (Ej: horas dormidas, cafés tomados, etc).",
    "¿Qué 'trend' de marketing te parece el más estúpido del momento?",
    "Si tuvieras que crear un grupo de música con 3 personas de la agencia, ¿quiénes serían y cómo se llamaría la banda?",
    "Confiesa un correo que desearías nunca haber enviado.",
    "¿Quién del equipo crees que podría vender su propia alma por un lead cualificado?",
    "Si un 'influencer' famoso tuviera que representar a nuestra agencia, ¿quién sería el que peor nos dejaría parados?",
    "¿Qué es lo más pasivo-agresivo que has escrito en un correo profesional?",
    "Si tuvieras que estar atrapado en una videollamada eterna con un cliente, ¿con cuál sería?",
    "¿Qué logro profesional de un compañero te da una envidia (sana o no tan sana)?",
    "Si tuvieras que reemplazar toda la música de los videos de un cliente con cumbia, ¿qué cliente sería el más gracioso?"
  ],
  "personal": [
    "¿Cuál es tu historial de búsqueda de Google más vergonzoso?",
    "¿Qué es lo peor que has hecho en casa de alguien sin que se dieran cuenta?",
    "Confiesa algo que sigues haciendo que es considerado 'infantil'.",
    "¿Cuál es la mentira más elaborada que has mantenido en tu vida personal?",
    "¿Qué es lo más raro que has comido estando borracho/a?",
    "Describe tu peor cita romántica en tres palabras.",
    "¿Cuál es la excusa más patética que has usado para cancelar un plan?",
    "¿Qué es algo que tus padres todavía no saben de ti?",
    "¿Cuál es el apodo más ridículo que te han puesto?",
    "Si tuvieras que mostrar la última foto de tu galería ahora mismo, ¿qué tan avergonzado/a estarías?",
    "¿Qué es algo que te obsesionaba de adolescente y que ahora te da cringe?",
    "¿Cuándo fue la última vez que lloraste y por qué motivo estúpido fue?",
    "Confiesa un placer culposo que nadie de los presentes conoce.",
    "¿Cuál es la teoría de conspiración más loca en la que crees un poquito?",
    "¿Qué es lo más ilegal que has hecho (y que pueda contarse)?",
    "Si tuvieras que leer en voz alta tus mensajes directos con tu 'crush', ¿qué parte omitirías?",
    "¿Cuál es el peor regalo que has recibido y tuviste que fingir que te gustaba?",
    "¿Qué es lo más vergonzoso que te ha pasado en un transporte público?",
    "Confiesa un 'secreto de higiene' que no le contarías a nadie.",
    "¿Cuál es la película o serie que te ha hecho llorar de forma desconsolada?",
    "Si tu vida sexual tuviera un título, ¿cuál sería?",
    "¿Qué es lo más estúpido por lo que has gastado una cantidad considerable de dinero?",
    "¿Cuál es tu técnica para librarte de una conversación aburrida en una fiesta?",
    "¿Qué es algo que finges que te gusta para encajar?",
    "¿Has 'stalkeado' a un ex y has dado un 'like' por accidente? ¿Cómo lo solucionaste?",
    "¿Cuál es el objeto más raro que tienes en tu mesita de noche?",
    "Confiesa una canción que cantas a todo pulmón cuando estás solo/a en casa.",
    "¿Cuál es la peor decisión de moda que has tomado en tu vida?",
    "¿Qué es lo más vergonzoso que tus padres te han hecho pasar delante de tus amigos?",
    "Si tuvieras que describir tu estado sentimental con el nombre de un postre, ¿cuál sería?",
    "¿Cuál es la habilidad más inútil que posees?",
    "¿Qué es lo más 'terco' o 'boomer' que haces o piensas?",
    "Si tuvieras que vivir dentro del último videojuego que jugaste, ¿qué tan rápido morirías?",
    "¿Cuál es el sueño más raro o perturbador que has tenido?",
    "Confiesa un miedo irracional que tienes (arañas y alturas no cuentan).",
    "¿Qué es lo peor que has cocinado y aun así te lo has comido?",
    "Si tuvieras que ponerle un 'disclaimer' a la gente antes de que te conozcan, ¿qué diría?",
    "¿Cuál es la cosa más extraña que has buscado en Wikipedia a altas horas de la noche?",
    "¿Qué es lo más vergonzoso que has hecho por dinero?",
    "Si tus mascotas pudieran hablar, ¿qué sería lo peor que dirían de ti?",
    "¿Cuál es el rumor más loco que ha circulado sobre ti?",
    "¿Qué es algo que te da una pereza extrema hacer, aunque sepas que es por tu bien?",
    "¿Cuál es la red social en la que proyectas una versión más falsa de ti mismo/a?",
    "Si tuvieras que crear un 'playlist' para tu funeral, ¿qué tres canciones no podrían faltar?",
    "¿Qué es algo que la mayoría de la gente ama pero que tú odias en secreto?",
    "¿Cuál es el audio de WhatsApp más vergonzoso que has enviado?",
    "Si tuvieras que donar un órgano para salvar a alguien, ¿a qué persona de esta llamada NO se lo donarías?",
    "¿Qué es lo más cerca que has estado de ser arrestado/a?",
    "¿Cuál es tu 'red flag' personal que sabes que tienes pero ignoras?",
    "Si tuvieras que salir en un programa de 'casos de familia', ¿cuál sería tu caso?",
    "¿Qué es algo que has roto en casa y le has echado la culpa a otra persona (o al perro)?",
    "¿Cuál es la peor borrachera de tu vida?",
    "Si pudieras borrar un recuerdo de tu mente para siempre, ¿cuál sería?",
    "¿Qué es lo más extraño que has hecho mientras estabas solo/a en casa?",
    "¿Cuál es tu manía más rara al comer?",
    "Si un genio te concediera un deseo estúpido, ¿qué le pedirías?",
    "¿Cuál es la compra online más impulsiva que has hecho?",
    "¿Qué es algo que te pone inexplicablemente nervioso/a?",
    "Si tuvieras que hacerte un tatuaje en la cara, ¿qué te tatuarías?",
    "Confiesa algo sobre ti que suene a mentira pero que sea 100% verdad."
  ],
  "gustos": [
    "¿Qué prefieres? ¿Tener la habilidad de volar, pero solo cuando estás completamente desnudo/a, o ser invisible, pero solo si gritas todo el tiempo?",
    "Si tuvieras que elegir, ¿preferirías tener que lamer el suelo del transporte público una vez o comer una pizza con cucarachas?",
    "¿Qué prefieres? ¿Saber la fecha exacta de tu muerte o la causa exacta de tu muerte?",
    "Si tuvieras que borrar de la existencia a una red social para siempre, ¿borrarías TikTok o Instagram?",
    "¿Qué prefieres? ¿Tener sexo increíble con alguien que odias o sexo mediocre con el amor de tu vida?",
    "Si solo pudieras escuchar a un artista por el resto de tu vida, ¿sería Bad Bunny o Ricardo Arjona?",
    "¿Qué prefieres? ¿Recibir un millón de dólares ahora mismo o la oportunidad de tener una cena de una hora con tu ídolo máximo?",
    "Si tuvieras que renunciar a una para siempre, ¿renunciarías a los tacos o a la pizza?",
    "¿Qué prefieres? ¿Vivir en el mundo de 'The Walking Dead' o en el de 'Mad Max'?",
    "Si tuvieras que llevar el mismo outfit por el resto de tu vida, ¿cuál sería?",
    "¿Qué prefieres? ¿Tener la capacidad de hablar con los animales o hablar fluidamente todos los idiomas humanos?",
    "Si tuvieras que salvar a una persona de un edificio en llamas, ¿salvarías a tu jefe o al cliente que nos da más dinero?",
    "¿Qué prefieres? ¿Tener un botón para rebobinar 10 segundos de tu vida a voluntad o un botón para pausar el tiempo por 10 segundos?",
    "Si tuvieras que perder un sentido, ¿perderías el gusto o el olfato?",
    "¿Qué prefieres? ¿Que tu vida sea narrada por Morgan Freeman o por el Pato Donald?",
    "Si el mundo se acabara y pudieras salvar el trabajo de un solo artista (música, cine, pintura), ¿el de quién salvarías?",
    "¿Qué prefieres? ¿Poder comer todo lo que quieras sin engordar o necesitar solo una hora de sueño para estar perfectamente descansado?",
    "Si tuvieras que elegir, ¿preferirías luchar contra un caballo del tamaño de un pato o contra cien patos del tamaño de un caballo?",
    "¿Qué prefieres? ¿Tener que decir siempre la verdad sin filtro o tener que mentir en cada frase que dices?",
    "Si tuvieras que vivir en una película para siempre, ¿sería en 'Shrek' o en 'Toy Story'?",
    "¿Qué prefieres? ¿Tener un millón de dólares pero no poder volver a usar internet o mantener tu vida como está?",
    "Si tuvieras que elegir tu última comida, ¿sería una bandeja paisa o un ceviche peruano?",
    "¿Qué prefieres? ¿Tener la contraseña del celular de tu pareja o que tu pareja tenga la tuya?",
    "Si tuvieras que ser un personaje secundario en una serie, ¿serías Gunther de 'Friends' o Creed de 'The Office'?",
    "¿Qué prefieres? ¿Saber todos los secretos del universo o tener paz mental infinita?",
    "Si tuvieras que eliminar una festividad del calendario, ¿eliminarías la Navidad o tu propio cumpleaños?",
    "¿Qué prefieres? ¿Que todos puedan escuchar tus pensamientos o que todos puedan ver a través de tus ojos?",
    "Si tuvieras que ver a tus padres teniendo sexo una vez o unirte a ellos, ¿qué elegirías?",
    "¿Qué prefieres? ¿Tener Wi-Fi gratis donde sea que vayas o tener batería ilimitada en todos tus dispositivos?",
    "Si tuvieras que reemplazar tus manos, ¿las reemplazarías con tenazas de cangrejo o con pies de bebé?",
    "¿Qué prefieres? ¿Ganar la lotería y que se entere todo el mundo o ganar la mitad pero que nadie lo sepa?",
    "Si tuvieras que tener una banda sonora para tu vida, ¿sería de reggaetón viejito o de pop de los 2000?",
    "¿Qué prefieres? ¿Salir en una cita con la persona más atractiva del mundo pero con la peor personalidad, o con alguien promedio pero increíblemente divertido?",
    "Si tuvieras que elegir un superpoder inútil, ¿cuál sería?",
    "¿Qué prefieres? ¿Vivir sin música o vivir sin queso?",
    "Si tuvieras que fusionar dos animales para crear la mascota perfecta, ¿cuáles serían?",
    "¿Qué prefieres? ¿Que te paguen por dormir o que te paguen por ver series?",
    "Si tuvieras que ser un meme por el resto de tu vida, ¿cuál serías?",
    "¿Qué prefieres? ¿Tener que oler a ajo por siempre o tener un sabor a cebolla en la boca por siempre?",
    "Si tuvieras que cometer un crimen y salirte con la tuya, ¿robarías un banco o filtrarías los secretos de un gobierno?",
    "¿Qué prefieres? ¿Viajar al pasado y conocer a tus ancestros o viajar al futuro y conocer a tus descendientes?",
    "Si tuvieras que elegir una habilidad de un videojuego para la vida real, ¿cuál sería?",
    "¿Qué prefieres? ¿No volver a sentir tristeza o no volver a sentir felicidad extrema?",
    "Si tuvieras que dirigir el 'remake' de una película clásica, ¿cuál arruinarías?",
    "¿Qué prefieres? ¿Tener siempre el pelo perfecto o tener siempre las uñas perfectas?",
    "Si tuvieras que sacrificar a un personaje de ficción para traer a otro de vuelta a la vida, ¿a quiénes elegirías?",
    "¿Qué prefieres? ¿Ser famoso a nivel mundial pero odiado, o ser un completo anónimo pero amado por tus cercanos?",
    "Si tuvieras que ponerle piña a una comida que no sea pizza, ¿a cuál sería?",
    "¿Qué prefieres? ¿Recibir un mal consejo de una persona sabia o un buen consejo de una persona estúpida?",
    "Si tuvieras que vivir en una década pasada, ¿serían los 80s o los 90s?",
    "¿Qué prefieres? ¿Tener un chef personal o un chofer personal?",
    "Si tuvieras que elegir entre la inmortalidad o tener 9 vidas como un gato, ¿qué elegirías?",
    "¿Qué prefieres? ¿Saber cómo vas a morir o cuándo vas a morir?",
    "Si tuvieras que ser alérgico a una cosa por el resto de tu vida, ¿sería al alcohol o al chocolate?",
    "¿Qué prefieres? ¿Tener que usar ropa mojada todos los lunes o no poder usar zapatos los viernes?",
    "Si tuvieras que traicionar a Batman o a Superman, ¿a quién traicionarías?",
    "¿Qué prefieres? ¿Tener la habilidad de teletransportarte pero con un 5% de probabilidad de aparecer en un lugar aleatorio del mundo, o volar a la velocidad de una bicicleta?",
    "Si tuvieras que cenar con tu 'celebrity crush' o con tu personaje de ficción favorito, ¿a quién elegirías?",
    "¿Qué prefieres? ¿Saber el final de todas las series y películas antes de verlas o nunca poder volver a ver un final?",
    "Si tuvieras que elegir un apocalipsis, ¿sería de zombies lentos o de robots inteligentes?"
  ]
}
